### ISSUE TITLE
doesn seem to do anything

### ISSUE THREAD

**Issue by sander76** [taichi/brackets-jsbeautifier#1]
...

**Comment by taichi** [comment]
...

**Comment by sander76** [comment]
Sorry. 
But I get a menu item including shortcut CTRL-SHIFT-B.
But on hitting it when inside an html document nothing happens. Could it be it is not for html ?

Sander.

**Comment by taichi** [comment]
thanks for your report. it's a bug.

**Comment by taichi** [comment]
fix bug and release 0.0.2.

please try it.
